
  name: tdlib Main
  on:
    push:
    workflow_dispatch:

  env:
    java_ver: "8"
    php_ver: "7.4"
    cmake_ver: "3.16.x"
    vcpkg_packages: "openssl zlib gperf readline --triplet x64-windows"


  jobs:
    build-td:
      runs-on: Windows-latest
      steps:

      - uses: actions/checkout@v3

# Install dependencies
      - uses: microsoft/setup-msbuild@v1.1
      - name: Test MSbuild
        run: msbuild -version

      - uses: lukka/get-cmake@latest
      - name: Test Cmake
        run: cmake --version

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: 'f93ba152d55e1d243160e690bc302ffe8638358e'
          vcpkgDirectory: ./vcpkg
      - name: Install dependencies from vcpkg
        run: "./vcpkg/vcpkg.exe install ${{ env.vcpkg_packages }} --clean-after-build"

      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.java_ver }}
      - name: Test Java
        run: "java -version"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_ver }}
      - name: Test PHP
        run: "php -v"

      - name: clean cache
        run: |
          rm -rf build CMakeFiles CMakeCache.txt
          find
          mkdir build
        shell: bash

# Compilation
      - name: Compile td with JNI support
        run: |
          cd ./build
          cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=../example/java/td -DTD_ENABLE_JNI=ON -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake ..
          cmake --build ../build --target install --config Release
          cd ..

      - name: Archive main td artifact
        uses: actions/upload-artifact@v3
        with:
          name: td
          path: ./build



    build-java:
      runs-on: Windows-latest
      steps:

      - uses: actions/checkout@v3

# Install dependencies
      - uses: microsoft/setup-msbuild@v1.1
      - name: Test MSbuild
        run: msbuild -version

      - uses: lukka/get-cmake@latest
      - name: Test Cmake
        run: cmake --version

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgGitCommitId: 'f93ba152d55e1d243160e690bc302ffe8638358e'
          vcpkgDirectory: ./vcpkg
      - name: Install dependencies from vcpkg
        run: "./vcpkg/vcpkg.exe install ${{ env.vcpkg_packages }} --clean-after-build"

      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.java_ver }}
      - name: Test Java
        run: "java -version"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.php_ver }}
      - name: Test PHP
        run: "php -v"


# Compilation
      - name: clean java cache
        run: |
          rm -rf ./example/java/build ./example/java/CMakeFiles ./example/java/CMakeCache.txt
          find
          mkdir ./example/java/build
        shell: bash
      - name: Compile Java ver
        run: |
          cd ./example/java/build
          cmake -A x64 -DCMAKE_INSTALL_PREFIX:PATH=tdlib -DCMAKE_TOOLCHAIN_FILE:FILEPATH=../vcpkg/scripts/buildsystems/vcpkg.cmake -DTd_DIR:PATH=$(Resolve-Path ../example/java/td/lib/cmake/Td) ../example/java
          cmake --build ../build --target install --config Release
          cd ../../..
          find ../tdlib
        shell: bash

      - name: Archive java artifact
        uses: actions/upload-artifact@v3
        with:
          name: tdJava
          path: ./example/java/build
