name: test_workflow
on: 
  push:

jobs:
  test:
    runs-on: windows-latest
    steps:
    - run: mkdir test1 test2 test3 test4 test5 test2/222 test4/333 test4/333/444
    - run: Get-ChildItem ./ -Filter *.txt -Recurse | % { $_.FullName }
    - run: echo $(powershell "Get-ChildItem ./ -Filter *.txt -Recurse | % { $_.FullName }")
      shell: bash
